version: '3.7'

services:
  akiraz-newsapp:
    image: akiraz-newsapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=database-mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    depends_on:
      - database-mysql

  database-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - db-akiraz-newsapp:/var/lib/mysql

volumes:
  db-akiraz-newsapp:
