TRUNCATE TABLE tbl_order;

INSERT INTO  tbl_order (ID,CUSTOMER_ID,BOOK_ID,ORDER_COUNT,CREATED_AT) 
			VALUES (100L, 1,72,1,sysdate);
			
INSERT INTO  tbl_order (ID,CUSTOMER_ID,BOOK_ID,ORDER_COUNT,CREATED_AT) 
			VALUES (101L, 3,72,1,ADD_MONTHS(SYSDATE,-3));
			
			
INSERT INTO  tbl_order (ID,CUSTOMER_ID,BOOK_ID,ORDER_COUNT,CREATED_AT) 
			VALUES (102L, 1,72,1,sysdate);
			
INSERT INTO  tbl_order (ID,CUSTOMER_ID,BOOK_ID,ORDER_COUNT,CREATED_AT) 
			VALUES (103L, 3,72,1,ADD_MONTHS(SYSDATE,-2));
			
INSERT INTO  tbl_order (ID,CUSTOMER_ID,BOOK_ID,ORDER_COUNT,CREATED_AT) 
			VALUES (104L, 3,72,1,ADD_MONTHS(SYSDATE,-2));
			
			
TRUNCATE TABLE tbl_book;


INSERT INTO  tbl_book (ID,NAME,DESCRIPTION,STOCK_COUNT,PRICE) 
			VALUES (72L, '1984','1984',100,50);
			
INSERT INTO  tbl_book (ID,NAME,DESCRIPTION,STOCK_COUNT,PRICE) 
			VALUES (75L, 'Little prince','Little prince',100,50);
			
			